/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(NI32, scoreMove)(NU8* data_p0, NI32 len_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, validateHeader__cost95pure_u32)(NU8* data_p0, NI32 len_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, readUint32__cost95pure_u28)(NU8* data_p0, NI32 offset_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u3758)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI32, readInt32__cost95pure_u8)(NU8* data_p0, NI32 offset_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3027)(Exception** dest_p0, Exception* src_p1);
N_LIB_EXPORT N_CDECL(NI32, evaluateHeuristic)(NU8* data_p0, NI32 len_p1);
N_LIB_EXPORT N_CDECL(NI32, checkInvariant)(NU8* data_p0, NI32 len_p1);
N_LIB_EXPORT N_CDECL(NI32, traceConsequences)(NU8* data_p0, NI32 len_p1);
extern NIM_THREADVAR TFrame* framePtr__system_u2770;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3566;
extern NIM_THREADVAR Exception* currException__system_u2997;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2770 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2770).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2770;
	framePtr__system_u2770 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u3758();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2770 = (*framePtr__system_u2770).prev;
}
N_LIB_PRIVATE N_NIMCALL(NU32, readUint32__cost95pure_u28)(NU8* data_p0, NI32 offset_p1) {
	NU32 result;
	nimfr_("readUint32", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
	nimlf_(25, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");	result = (*((NU32*) ((&data_p0[offset_p1]))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, readInt32__cost95pure_u8)(NU8* data_p0, NI32 offset_p1) {
	NI32 result;
	nimfr_("readInt32", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
	nimln_(21);	result = (*((NI32*) ((&data_p0[offset_p1]))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3566);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, validateHeader__cost95pure_u32)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NU32 magic_1;
	NI32 totalLen_1;
NIM_BOOL* nimErr_;
	nimfr_("validateHeader", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(30);	{
		if (!(len_p1 < ((NI32)8))) goto LA3_;
		nimln_(31);		nimln_(27);		nimln_(31);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(32);	magic_1 = readUint32__cost95pure_u28(data_p0, ((NI32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(33);	{
		if (!!((magic_1 == ((NU32)1096304973)))) goto LA7_;
		nimln_(34);		nimln_(27);		nimln_(34);		result = ((NI32)-2);
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(35);	totalLen_1 = readInt32__cost95pure_u8(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(36);	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = (len_p1 < totalLen_1);
		if (T11_) goto LA12_;
		T11_ = (totalLen_1 < ((NI32)8));
LA12_: ;
		if (!T11_) goto LA13_;
		nimln_(37);		nimln_(27);		nimln_(37);		result = ((NI32)-3);
		goto BeforeRet_;
	}
LA13_: ;
	nimln_(38);	nimln_(27);	nimln_(38);	result = ((NI32)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(288, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	nimfr_("nimBorrowCurrentException", "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimlf_(2371, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	result = currException__system_u2997;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3027(&currException__system_u2997, (*currException__system_u2997).up);
}
N_LIB_EXPORT N_CDECL(NI32, scoreMove)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T7_;
	NI32 payloadLen_1;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_2;
	NI32 score_1;
	NI32 T12_;
NIM_BOOL* nimErr_;
	nimfr_("scoreMove", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimlf_(44, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");	T2_ = (NI32)0;
	T2_ = validateHeader__cost95pure_u32(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(45);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(40);		nimln_(45);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(46);	T7_ = (NI32)0;
	T7_ = readInt32__cost95pure_u8(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T7_;
	nimln_(47);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_2)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_2 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_2 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_2);
	nimln_(48);	{
		if (!(payloadLen_1 < ((NI32)4))) goto LA10_;
		nimln_(40);		nimln_(48);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA10_: ;
	nimln_(50);	T12_ = (NI32)0;
	T12_ = readInt32__cost95pure_u8(data_p0, ((NI32)8));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	score_1 = T12_;
	nimln_(51);	{
		if (!(score_1 < ((NI32)0))) goto LA15_;
		nimln_(40);		nimln_(51);		result = ((NI32)0);
		goto BeforeRet_;
	}
LA15_: ;
	nimln_(52);	nimln_(40);	nimln_(52);	result = score_1;
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(54);			nimln_(40);			nimln_(54);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA18_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(56);			nimln_(40);			nimln_(56);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA20_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, evaluateHeuristic)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T7_;
	NI32 payloadLen_1;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_3;
	NI32 a_1;
	NI32 T12_;
	NI32 b_1;
	NI32 T13_;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_4;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_5;
NIM_BOOL* nimErr_;
	nimfr_("evaluateHeuristic", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(61);	T2_ = (NI32)0;
	T2_ = validateHeader__cost95pure_u32(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(62);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(58);		nimln_(62);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(63);	T7_ = (NI32)0;
	T7_ = readInt32__cost95pure_u8(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T7_;
	nimln_(64);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_3)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_3 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_3 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_3);
	nimln_(65);	{
		if (!(payloadLen_1 < ((NI32)8))) goto LA10_;
		nimln_(58);		nimln_(65);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA10_: ;
	nimln_(67);	T12_ = (NI32)0;
	T12_ = readInt32__cost95pure_u8(data_p0, ((NI32)8));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	a_1 = T12_;
	nimln_(68);	T13_ = (NI32)0;
	T13_ = readInt32__cost95pure_u8(data_p0, ((NI32)12));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	b_1 = T13_;
	nimln_(70);	nimln_(58);	nimln_(70);	if (nimMulInt(a_1, ((NI32)3), &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_4)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_4 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_4 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	if (nimAddInt((NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_4), b_1, &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_5)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_5 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_5 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	result = (NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_5);
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(72);			nimln_(58);			nimln_(72);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA15_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(74);			nimln_(58);			nimln_(74);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA17_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, checkInvariant)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T7_;
	NI32 payloadLen_1;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_6;
	NI32 value_1;
	NI32 T12_;
NIM_BOOL* nimErr_;
	nimfr_("checkInvariant", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(80);	T2_ = (NI32)0;
	T2_ = validateHeader__cost95pure_u32(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(81);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(76);		nimln_(81);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(82);	T7_ = (NI32)0;
	T7_ = readInt32__cost95pure_u8(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T7_;
	nimln_(83);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_6)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_6 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_6 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_6);
	nimln_(84);	{
		if (!(payloadLen_1 < ((NI32)4))) goto LA10_;
		nimln_(76);		nimln_(84);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA10_: ;
	nimln_(85);	T12_ = (NI32)0;
	T12_ = readInt32__cost95pure_u8(data_p0, ((NI32)8));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	value_1 = T12_;
	nimln_(87);	{
		if (!(value_1 < ((NI32)0))) goto LA15_;
		nimln_(76);		nimln_(87);		result = ((NI32)1);
		goto BeforeRet_;
	}
LA15_: ;
	nimln_(88);	nimln_(76);	nimln_(88);	result = ((NI32)0);
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(90);			nimln_(76);			nimln_(90);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA18_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(92);			nimln_(76);			nimln_(92);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA20_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, traceConsequences)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T7_;
	NI32 payloadLen_1;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_7;
	NI32 depth_1;
	NI32 T12_;
	NI TM__PxH5ZLG9avnWLFzBIkMw9b3Q_8;
NIM_BOOL* nimErr_;
	nimfr_("traceConsequences", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/cost_pure.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(98);	T2_ = (NI32)0;
	T2_ = validateHeader__cost95pure_u32(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(99);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(94);		nimln_(99);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(100);	T7_ = (NI32)0;
	T7_ = readInt32__cost95pure_u8(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T7_;
	nimln_(101);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_7)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_7 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_7 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_7);
	nimln_(102);	{
		if (!(payloadLen_1 < ((NI32)4))) goto LA10_;
		nimln_(94);		nimln_(102);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA10_: ;
	nimln_(103);	T12_ = (NI32)0;
	T12_ = readInt32__cost95pure_u8(data_p0, ((NI32)8));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	depth_1 = T12_;
	nimln_(104);	{
		if (!(depth_1 < ((NI32)0))) goto LA15_;
		nimln_(94);		nimln_(104);		result = ((NI32)0);
		goto BeforeRet_;
	}
LA15_: ;
	nimln_(106);	nimln_(94);	nimln_(106);	if (nimMulInt(depth_1, ((NI32)2), &TM__PxH5ZLG9avnWLFzBIkMw9b3Q_8)) { raiseOverflow(); goto LA1_;
	};
	if (TM__PxH5ZLG9avnWLFzBIkMw9b3Q_8 < (-2147483647 -1) || TM__PxH5ZLG9avnWLFzBIkMw9b3Q_8 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	result = (NI32)(TM__PxH5ZLG9avnWLFzBIkMw9b3Q_8);
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(108);			nimln_(94);			nimln_(108);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA18_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(110);			nimln_(94);			nimln_(110);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA20_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
