/* Generated by Nim Compiler v2.2.10 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(NI32, computeStateHash)(NU8* data_p0, NI32 len_p1, NU8* outHash_p2, NI32 hashLen_p3);
N_LIB_PRIVATE N_NIMCALL(NI32, validateHeader__snapshot_u19)(NU8* data_p0, NI32 len_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, readUint32__snapshot_u15)(NU8* data_p0, NI32 offset_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u3758)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI32, readInt32__snapshot_u11)(NU8* data_p0, NI32 offset_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3027)(Exception** dest_p0, Exception* src_p1);
N_LIB_EXPORT N_CDECL(NI32, validateSnapshot)(NU8* data_p0, NI32 len_p1);
N_LIB_EXPORT N_CDECL(NI32, applyEvents)(NU8* snapshotData_p0, NI32 snapshotLen_p1, NU8* eventsData_p2, NI32 eventsLen_p3, NU8* outData_p4, NI32 outLen_p5);
N_LIB_EXPORT N_CDECL(NI32, migrateSnapshot)(NU8* data_p0, NI32 len_p1, NI32 fromVersion_p2, NI32 toVersion_p3, NU8* outData_p4, NI32 outLen_p5);
extern NIM_THREADVAR TFrame* framePtr__system_u2770;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u3566;
extern NIM_THREADVAR Exception* currException__system_u2997;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2770 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2770).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2770;
	framePtr__system_u2770 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u3758();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2770 = (*framePtr__system_u2770).prev;
}
N_LIB_PRIVATE N_NIMCALL(NU32, readUint32__snapshot_u15)(NU8* data_p0, NI32 offset_p1) {
	NU32 result;
	nimfr_("readUint32", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
	nimlf_(28, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");	result = (*((NU32*) ((&data_p0[offset_p1]))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, readInt32__snapshot_u11)(NU8* data_p0, NI32 offset_p1) {
	NI32 result;
	nimfr_("readInt32", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
	nimln_(24);	result = (*((NI32*) ((&data_p0[offset_p1]))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3566);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, validateHeader__snapshot_u19)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NU32 magic_1;
	NI32 totalLen_1;
NIM_BOOL* nimErr_;
	nimfr_("validateHeader", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(33);	{
		if (!(len_p1 < ((NI32)8))) goto LA3_;
		nimln_(34);		nimln_(30);		nimln_(34);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(35);	magic_1 = readUint32__snapshot_u15(data_p0, ((NI32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(36);	{
		if (!!((magic_1 == ((NU32)1096304973)))) goto LA7_;
		nimln_(37);		nimln_(30);		nimln_(37);		result = ((NI32)-2);
		goto BeforeRet_;
	}
LA7_: ;
	nimln_(38);	totalLen_1 = readInt32__snapshot_u11(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(39);	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = (len_p1 < totalLen_1);
		if (T11_) goto LA12_;
		T11_ = (totalLen_1 < ((NI32)8));
LA12_: ;
		if (!T11_) goto LA13_;
		nimln_(40);		nimln_(30);		nimln_(40);		result = ((NI32)-3);
		goto BeforeRet_;
	}
LA13_: ;
	nimln_(41);	nimln_(30);	nimln_(41);	result = ((NI32)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isObjDisplayCheck", "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");
	nimlf_(288, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	popFrame();
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	nimfr_("nimBorrowCurrentException", "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimlf_(2371, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	result = currException__system_u2997;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3027(&currException__system_u2997, (*currException__system_u2997).up);
}
N_LIB_EXPORT N_CDECL(NI32, computeStateHash)(NU8* data_p0, NI32 len_p1, NU8* outHash_p2, NI32 hashLen_p3) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T11_;
	NI32 payloadLen_1;
	NI TM__m59bWhzAXS04L9abvSoBjvhA_2;
	NU64 h_1;
NIM_BOOL* nimErr_;
	nimfr_("computeStateHash", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimlf_(49, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");	T2_ = (NI32)0;
	T2_ = validateHeader__snapshot_u19(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(50);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(43);		nimln_(50);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(51);	{
		if (!(hashLen_p3 < ((NI32)40))) goto LA9_;
		nimln_(43);		nimln_(51);		result = ((NI32)-6);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(52);	T11_ = (NI32)0;
	T11_ = readInt32__snapshot_u11(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T11_;
	nimln_(53);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__m59bWhzAXS04L9abvSoBjvhA_2)) { raiseOverflow(); goto LA1_;
	};
	if (TM__m59bWhzAXS04L9abvSoBjvhA_2 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_2 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_2);
	nimln_(54);	{
		if (!(payloadLen_1 <= ((NI32)0))) goto LA14_;
		nimln_(43);		nimln_(54);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA14_: ;
	nimln_(56);	h_1 = 14695981039346656037ULL;
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		nimlf_(137, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI32)8);
		{
			nimln_(138);			while (1) {
				NI TM__m59bWhzAXS04L9abvSoBjvhA_3;
				if (!(res_1 < totalLen_1)) goto LA18;
				nimlf_(57, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");				i_1 = res_1;
				nimln_(58);				h_1 = (NU64)(h_1 ^ ((NU64) (data_p0[i_1])));
				nimln_(59);				h_1 = (NU64)((NU64)(h_1) * (NU64)(1099511628211ULL));
				nimln_(60);				h_1 = (NU64)(h_1 ^ (NU64)((NU64)(h_1) >> (NU64)(((NI)16) & (64 - 1))));
				nimlf_(140, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__m59bWhzAXS04L9abvSoBjvhA_3)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_3 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_3 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				res_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_3);
			} LA18: ;
		}
	}
	{
		NI32 i_2;
		NI32 res_2;
		i_2 = (NI32)0;
		nimln_(137);		res_2 = ((NI32)0);
		{
			nimln_(138);			while (1) {
				NU64 mixed_1;
				NI TM__m59bWhzAXS04L9abvSoBjvhA_4;
				if (!(res_2 < ((NI32)40))) goto LA21;
				nimlf_(62, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");				i_2 = res_2;
				nimln_(63);				mixed_1 = (NU64)(h_1 ^ (NU64)((NU64)(((NU64) (i_2))) * (NU64)(11400714819323198485ULL)));
				nimln_(64);				outHash_p2[i_2] = ((NU8) ((NU64)(mixed_1 & 255ULL)));
				nimlf_(140, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_2, ((NI)1), &TM__m59bWhzAXS04L9abvSoBjvhA_4)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_4 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_4 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				res_2 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_4);
			} LA21: ;
		}
	}
	nimlf_(65, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");	nimln_(43);	nimln_(65);	result = ((NI32)0);
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(67);			nimln_(43);			nimln_(67);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA23_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(69);			nimln_(43);			nimln_(69);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA25_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, validateSnapshot)(NU8* data_p0, NI32 len_p1) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T7_;
	NI32 payloadLen_1;
	NI TM__m59bWhzAXS04L9abvSoBjvhA_5;
NIM_BOOL* nimErr_;
	nimfr_("validateSnapshot", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(75);	T2_ = (NI32)0;
	T2_ = validateHeader__snapshot_u19(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(76);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(71);		nimln_(76);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(77);	T7_ = (NI32)0;
	T7_ = readInt32__snapshot_u11(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T7_;
	nimln_(78);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__m59bWhzAXS04L9abvSoBjvhA_5)) { raiseOverflow(); goto LA1_;
	};
	if (TM__m59bWhzAXS04L9abvSoBjvhA_5 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_5 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_5);
	nimln_(79);	{
		if (!(payloadLen_1 <= ((NI32)0))) goto LA10_;
		nimln_(71);		nimln_(79);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA10_: ;
	nimln_(81);	{
		NIM_BOOL T14_;
		NI TM__m59bWhzAXS04L9abvSoBjvhA_6;
		T14_ = (NIM_BOOL)0;
		T14_ = !((data_p0[((NI32)8)] == ((NU8)123)));
		if (T14_) goto LA15_;
		if (nimSubInt(totalLen_1, ((NI32)1), &TM__m59bWhzAXS04L9abvSoBjvhA_6)) { raiseOverflow(); goto LA1_;
		};
		if (TM__m59bWhzAXS04L9abvSoBjvhA_6 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_6 > 2147483647){ raiseOverflow(); goto LA1_;
		}
		T14_ = !((data_p0[(NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_6)] == ((NU8)125)));
LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(82);		nimln_(71);		nimln_(82);		result = ((NI32)-4);
		goto BeforeRet_;
	}
LA16_: ;
	nimln_(83);	nimln_(71);	nimln_(83);	result = ((NI32)0);
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(85);			nimln_(71);			nimln_(85);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA19_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(87);			nimln_(71);			nimln_(87);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA21_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, applyEvents)(NU8* snapshotData_p0, NI32 snapshotLen_p1, NU8* eventsData_p2, NI32 eventsLen_p3, NU8* outData_p4, NI32 outLen_p5) {
	NI32 result;
	NI32 err1_1;
	NI32 T2_;
	NI32 err2_1;
	NI32 T7_;
	NI32 totalLen_1;
	NI32 T12_;
	NI32 payloadLen_1;
	NI TM__m59bWhzAXS04L9abvSoBjvhA_7;
	NI32 frameSize_1;
	NI TM__m59bWhzAXS04L9abvSoBjvhA_8;
NIM_BOOL* nimErr_;
	nimfr_("applyEvents", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(96);	T2_ = (NI32)0;
	T2_ = validateHeader__snapshot_u19(snapshotData_p0, snapshotLen_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err1_1 = T2_;
	nimln_(97);	{
		if (!!((err1_1 == ((NI32)0)))) goto LA5_;
		nimln_(89);		nimln_(97);		result = err1_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(98);	T7_ = (NI32)0;
	T7_ = validateHeader__snapshot_u19(eventsData_p2, eventsLen_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err2_1 = T7_;
	nimln_(99);	{
		if (!!((err2_1 == ((NI32)0)))) goto LA10_;
		nimln_(89);		nimln_(99);		result = err2_1;
		goto BeforeRet_;
	}
LA10_: ;
	nimln_(100);	T12_ = (NI32)0;
	T12_ = readInt32__snapshot_u11(snapshotData_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T12_;
	nimln_(101);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__m59bWhzAXS04L9abvSoBjvhA_7)) { raiseOverflow(); goto LA1_;
	};
	if (TM__m59bWhzAXS04L9abvSoBjvhA_7 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_7 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_7);
	nimln_(102);	{
		if (!(payloadLen_1 <= ((NI32)0))) goto LA15_;
		nimln_(89);		nimln_(102);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA15_: ;
	nimln_(103);	if (nimAddInt(payloadLen_1, ((NI32)8), &TM__m59bWhzAXS04L9abvSoBjvhA_8)) { raiseOverflow(); goto LA1_;
	};
	if (TM__m59bWhzAXS04L9abvSoBjvhA_8 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_8 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	frameSize_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_8);
	nimln_(104);	{
		if (!(outLen_p5 < frameSize_1)) goto LA19_;
		nimln_(89);		nimln_(104);		result = ((NI32)-6);
		goto BeforeRet_;
	}
LA19_: ;
	nimln_(106);	(*((NU32*) ((&outData_p4[((NI)0)])))) = ((NU32)1096304973);
	nimln_(107);	(*((NI32*) ((&outData_p4[((NI)4)])))) = frameSize_1;
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		nimlf_(137, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI32)0);
		{
			nimln_(138);			while (1) {
				NI TM__m59bWhzAXS04L9abvSoBjvhA_9;
				NI TM__m59bWhzAXS04L9abvSoBjvhA_10;
				NI TM__m59bWhzAXS04L9abvSoBjvhA_11;
				if (!(res_1 < payloadLen_1)) goto LA23;
				nimlf_(109, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");				i_1 = res_1;
				nimln_(110);				if (nimAddInt(((NI32)8), i_1, &TM__m59bWhzAXS04L9abvSoBjvhA_9)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_9 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_9 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				if (nimAddInt(((NI32)8), i_1, &TM__m59bWhzAXS04L9abvSoBjvhA_10)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_10 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_10 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				outData_p4[(NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_9)] = snapshotData_p0[(NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_10)];
				nimlf_(140, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__m59bWhzAXS04L9abvSoBjvhA_11)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_11 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_11 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				res_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_11);
			} LA23: ;
		}
	}
	nimlf_(111, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");	nimln_(89);	nimln_(111);	result = frameSize_1;
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(113);			nimln_(89);			nimln_(113);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA25_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(115);			nimln_(89);			nimln_(115);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA27_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, migrateSnapshot)(NU8* data_p0, NI32 len_p1, NI32 fromVersion_p2, NI32 toVersion_p3, NU8* outData_p4, NI32 outLen_p5) {
	NI32 result;
	NI32 err_1;
	NI32 T2_;
	NI32 totalLen_1;
	NI32 T15_;
	NI32 payloadLen_1;
	NI TM__m59bWhzAXS04L9abvSoBjvhA_12;
	NI32 frameSize_1;
	NI TM__m59bWhzAXS04L9abvSoBjvhA_13;
NIM_BOOL* nimErr_;
	nimfr_("migrateSnapshot", "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(124);	T2_ = (NI32)0;
	T2_ = validateHeader__snapshot_u19(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	err_1 = T2_;
	nimln_(125);	{
		if (!!((err_1 == ((NI32)0)))) goto LA5_;
		nimln_(117);		nimln_(125);		result = err_1;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(126);	{
		NIM_BOOL T9_;
		NIM_BOOL T10_;
		T9_ = (NIM_BOOL)0;
		T10_ = (NIM_BOOL)0;
		T10_ = (fromVersion_p2 < ((NI32)1));
		if (T10_) goto LA11_;
		T10_ = (toVersion_p3 < ((NI32)1));
LA11_: ;
		T9_ = T10_;
		if (T9_) goto LA12_;
		T9_ = (toVersion_p3 < fromVersion_p2);
LA12_: ;
		if (!T9_) goto LA13_;
		nimln_(127);		nimln_(117);		nimln_(127);		result = ((NI32)-5);
		goto BeforeRet_;
	}
LA13_: ;
	nimln_(128);	T15_ = (NI32)0;
	T15_ = readInt32__snapshot_u11(data_p0, ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	totalLen_1 = T15_;
	nimln_(129);	if (nimSubInt(totalLen_1, ((NI32)8), &TM__m59bWhzAXS04L9abvSoBjvhA_12)) { raiseOverflow(); goto LA1_;
	};
	if (TM__m59bWhzAXS04L9abvSoBjvhA_12 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_12 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	payloadLen_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_12);
	nimln_(130);	{
		if (!(payloadLen_1 <= ((NI32)0))) goto LA18_;
		nimln_(117);		nimln_(130);		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA18_: ;
	nimln_(131);	if (nimAddInt(payloadLen_1, ((NI32)8), &TM__m59bWhzAXS04L9abvSoBjvhA_13)) { raiseOverflow(); goto LA1_;
	};
	if (TM__m59bWhzAXS04L9abvSoBjvhA_13 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_13 > 2147483647){ raiseOverflow(); goto LA1_;
	}
	frameSize_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_13);
	nimln_(132);	{
		if (!(outLen_p5 < frameSize_1)) goto LA22_;
		nimln_(117);		nimln_(132);		result = ((NI32)-6);
		goto BeforeRet_;
	}
LA22_: ;
	nimln_(134);	(*((NU32*) ((&outData_p4[((NI)0)])))) = ((NU32)1096304973);
	nimln_(135);	(*((NI32*) ((&outData_p4[((NI)4)])))) = frameSize_1;
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		nimlf_(137, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI32)0);
		{
			nimln_(138);			while (1) {
				NI TM__m59bWhzAXS04L9abvSoBjvhA_14;
				NI TM__m59bWhzAXS04L9abvSoBjvhA_15;
				NI TM__m59bWhzAXS04L9abvSoBjvhA_16;
				if (!(res_1 < payloadLen_1)) goto LA26;
				nimlf_(137, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");				i_1 = res_1;
				nimln_(138);				if (nimAddInt(((NI32)8), i_1, &TM__m59bWhzAXS04L9abvSoBjvhA_14)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_14 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_14 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				if (nimAddInt(((NI32)8), i_1, &TM__m59bWhzAXS04L9abvSoBjvhA_15)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_15 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_15 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				outData_p4[(NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_14)] = data_p0[(NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_15)];
				nimlf_(140, "/home/wintrover/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__m59bWhzAXS04L9abvSoBjvhA_16)) { raiseOverflow(); goto LA1_;
				};
				if (TM__m59bWhzAXS04L9abvSoBjvhA_16 < (-2147483647 -1) || TM__m59bWhzAXS04L9abvSoBjvhA_16 > 2147483647){ raiseOverflow(); goto LA1_;
				}
				res_1 = (NI32)(TM__m59bWhzAXS04L9abvSoBjvhA_16);
			} LA26: ;
		}
	}
	nimlf_(139, "/home/wintrover/.kimi-code/src/kimi-code/packages/agent-core/native/nim/src/snapshot.nim");	nimln_(117);	nimln_(139);	result = frameSize_1;
	goto BeforeRet_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 4118291968)) {
			*nimErr_ = NIM_FALSE;
			nimln_(141);			nimln_(117);			nimln_(141);			result = ((NI32)-998);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA28_:;
		}
		else 		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 2, 2897559296)) {
			*nimErr_ = NIM_FALSE;
			nimln_(143);			nimln_(117);			nimln_(143);			result = ((NI32)-999);
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA30_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
